[package]
name = "multihash"
description = "Implementation of the multihash format"
repository = "https://github.com/multiformats/rust-multihash"
keywords = ["multihash", "ipfs"]
version = "0.8.1-pre"
authors = ["dignifiedquire <dignifiedquire@gmail.com>"]
license = "MIT"
readme = "README.md"
documentation = "https://docs.rs/multihash/"
edition = "2018"

[dependencies]
blake2 = { version = "0.8", default-features = false }
digest = { version = "0.8", default-features = false }
failure = { version = "0.1", default-features = false }
fasthash = "0.4"
integer-encoding = { version = "1.0", default-features = false }
multihash_derive = { path = "./multihash_derive" }
rand = { version = "0.7", optional = true }
sha-1 ={ version = "0.8", default-features = false }
sha2 = { version = "0.8", default-features = false }
sha3 = { version = "0.8", default-features = false }

[dev-dependencies]
hex = "0.3"

[features]
default = ["std", "derive", "random"]
derive = ["failure/derive"]
std = ["sha-1/std", "blake2/std", "sha3/std", "sha2/std", "failure/std", "digest/std"]
simd = ["blake2/simd_opt"]
asm = ["sha2/asm", "blake2/simd_asm"]
random = ["rand"]

[workspace]
members = [
  "cli",
  "multihash_derive",
]
