[package]
name = "multihash"
description = "Implementation of the multihash format"
homepage = "https://github.com/multiformats/rust-multihash"

keywords = ["multihash", "ipfs"]

version = "0.4.2"

authors = ["dignifiedquire <dignifiedquire@gmail.com>"]

license = "MIT"

readme = "README.md"

[dependencies]
tiny-keccak = "~1.0.5"
ring = "~0.6.2"
