[package]
name = "multihash-derive"
version = "0.8.1"
authors = ["David Craven <david@craven.ch>"]
edition = "2018"
description = "Proc macro for deriving custom multihash tables."
license = "MIT"
repository = "https://github.com/multiformats/multihash"
resolver = "2"

[dependencies]
multihash-derive-impl = { version = "0.1.0", path = "../derive-impl" }
multihash = { version = "0.18.0", path = "../" }
